### ISSUE TITLE
ILoggingBuilder API instead of obsolete ILoggerFactory

### ISSUE THREAD

**Issue by valery-vitko** [Steinpilz/confifu-logging#1]
MS made ILoggerFactory obsolete and [removing it in ASP.NET Core 3](https://github.com/aspnet/Extensions/pull/477) and replacing it with `ILoggingBuilder`.

Thus I'm proposing to:
1) update Microsoft.Extensions.Logging.* dependencies versions to 2.2.0 to allow `ILoggingBuilder` usage;
1) change Confifu API's to use `ILoggingBuilder` instead of `ILoggerFactory`.
1) since changes above are breaking ones, update Confifu.Abstractions.Logging and Confifu.Logging.Microsoft version to 2.0.0.

@ivanbenko, if you agree with the points above, I'd be glad to provide a PR.

**Comment by ivanbenko** [comment]
@valery-vitko sounds cool. 
ps. I compared Microsoft.Extensions.Logging.* dlls 1.1.2 with 2.2.0 few weeks ago in terms of runtime compatibility, and there no breaking changes. But yea, Confifu.* version should be increased to 2.0.0
